package com.smartstudy.dao;
import com.smartstudy.config.Database;
import com.smartstudy.model.Student;
import java.sql.*; import java.util.*;
public final class StudentDao {
    private Student map(ResultSet r) throws SQLException { return new Student(r.getInt("student_id"), r.getString("full_name"), r.getString("email"), r.getString("password_hash"), r.getDouble("available_hours"), r.getBoolean("is_active"), r.getBoolean("email_notifications"), r.getBoolean("in_app_notifications"), r.getBoolean("weekly_summary")); }
    public Optional<Student> findByEmail(String email) throws SQLException { try(Connection c=Database.getConnection(); PreparedStatement p=c.prepareStatement("SELECT * FROM students WHERE LOWER(email)=LOWER(?)")){p.setString(1,email);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}} }
    public Optional<Student> findById(int id) throws SQLException { try(Connection c=Database.getConnection(); PreparedStatement p=c.prepareStatement("SELECT * FROM students WHERE student_id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}} }
    public Student create(String name,String email,String hash,double hours) throws SQLException { String q="INSERT INTO students(full_name,email,password_hash,available_hours) VALUES(?,?,?,?)"; try(Connection c=Database.getConnection(); PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setString(1,name);p.setString(2,email);p.setString(3,hash);p.setDouble(4,hours);p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){k.next();return findById(k.getInt(1)).orElseThrow();}} }
    public void updateProfile(Student s) throws SQLException { String q="UPDATE students SET full_name=?,password_hash=?,available_hours=?,email_notifications=?,in_app_notifications=?,weekly_summary=? WHERE student_id=?"; try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,s.fullName());p.setString(2,s.passwordHash());p.setDouble(3,s.availableHours());p.setBoolean(4,s.emailNotifications());p.setBoolean(5,s.inAppNotifications());p.setBoolean(6,s.weeklySummary());p.setInt(7,s.studentId());p.executeUpdate();} }
    public List<Student> findAll() throws SQLException { List<Student> out=new ArrayList<>();try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM students ORDER BY full_name");ResultSet r=p.executeQuery()){while(r.next())out.add(map(r));}return out; }
    public void setActive(int id,boolean active) throws SQLException { try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("UPDATE students SET is_active=? WHERE student_id=?")){p.setBoolean(1,active);p.setInt(2,id);p.executeUpdate();} }
    public void delete(int id) throws SQLException { try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM students WHERE student_id=?")){p.setInt(1,id);p.executeUpdate();} }
}
